from pydantic import BaseModel, EmailStr
from typing import List, Optional, Dict


class EmailRecipient(BaseModel):
    name: str
    email_id: EmailStr


class RfqItemDetails(BaseModel):
    Description: str
    ItemTypeFK: int
    PartLength: Optional[float]
    PartNumber: str
    PartWidth: Optional[float]
    PurchaseOrderComment: Optional[str]
    QuantityRequired: float
    StockLength: Optional[float]
    StockWidth: Optional[float]
    Thickness: Optional[float]

    # generated by code internally.
    Category: Optional[str]
    EmailCategory: Optional[str]

    def material(self) -> Dict:
        return {
            "PartNumber": self.PartNumber,
            "Material": self.Description,
            "QTY": str(self.QuantityRequired),
            "StockSize": rf"{self.StockLength} x {self.StockWidth} x {self.Thickness}",
            "Domestic": "Yes",
            "Group": self.Category
        }

    def fin(self) -> Dict:
        return {
            "PartNumber": self.PartNumber,
            "QTY": str(self.QuantityRequired),
            "Finish": self.Description,
            "PartSize": rf"{self.StockLength} x {self.StockWidth} x {self.Thickness}"
        }

    def ht(self) -> Dict:
        return {
            "PartNumber": self.PartNumber,
            "HeatTreatProcess": self.Description,
            "QTY": self.QuantityRequired,
            "PartSize": rf"{self.StockLength} x {self.StockWidth} x {self.Thickness}"
        }

    def hardware(self) -> Dict:
        return {
            "Hardware": self.Description,
            "QTY": self.QuantityRequired,
            "ParentPN": self.PartNumber,
        }


class RFQItem(BaseModel):
    """
    Data class to represent RFQ line items.
    """
    item_pk: int
    part_number: str
    qty: float  # aggregated QTY
    code: Optional[str] = None
    comments: str = ""
    item_details: Optional[RfqItemDetails] = None


class RFQItemGroup(BaseModel):
    code: str
    items: List[RFQItem]
    emails: List[EmailRecipient]

